#!/usr/bin/env node
/**
 * build-adblocker.js
 * 
 * Full working single‑file script that:
 * 1. Downloads easylist.txt from https://easylist.to/easylist/easylist.txt
 * 2. Parses all element‑hiding rules (lines starting with "##")
 * 3. Generates a browser‑compatible adblocker.js with those selectors
 * 
 * Run: node build-adblocker.js
 * Output: adblocker.js (ready to be included in your HTML)
 */

"use strict";

const request = require('request');
const fs = require('fs');
const path = require('path');

// ------------------------------------------------------------------
// 1. Download EasyList
// ------------------------------------------------------------------
function downloadEasyList(callback) {
    const url = 'https://easylist.to/easylist/easylist.txt';
    console.log('[build] Downloading EasyList from', url);
    request(url, (err, resp, body) => {
        if (err) {
            console.error('[build] Download failed:', err.message);
            return callback(err);
        }
        console.log('[build] Download completed (%d bytes)', body.length);
        callback(null, body);
    });
}

// ------------------------------------------------------------------
// 2. Parse element‑hiding rules from the raw list
//    Returns an array of CSS selectors (without the "##" prefix)
// ------------------------------------------------------------------
function parseEasyList(text) {
    const lines = text.split(/\r?\n/);
    const selectors = [];

    for (let line of lines) {
        line = line.trim();
        // Ignore empty lines, comments, and exception rules (##@)
        if (!line || line.startsWith('!') || line.startsWith('[Adblock') || line.startsWith('#')) {
            continue;
        }
        // We only want element‑hiding rules: lines that start with "##" but not "##@"
        if (line.startsWith('##') && !line.startsWith('##@')) {
            // Remove the "##" prefix to get the CSS selector
            const selector = line.slice(2);
            // Skip extremely generic selectors that might break the page
            if (selector === 'body' || selector === 'html' || selector === '*') {
                continue;
            }
            selectors.push(selector);
        }
    }
    console.log('[build] Extracted %d element‑hiding selectors', selectors.length);
    return selectors;
}

// ------------------------------------------------------------------
// 3. Generate the final adblocker.js file
//    It contains the same logic as the original client script,
//    but with the dynamically fetched selectors.
// ------------------------------------------------------------------
function generateAdblocker(selectors, outputPath) {
    // Escape single quotes in selectors (for the array literal)
    const escapedSelectors = selectors.map(s => s.replace(/'/g, "\\'"));

    // Build the full client script (identical to the provided one,
    // with the selector array replaced)
    const clientScript = `/**
 * adblocker.js – generated by build-adblocker.js
 * Uses the latest EasyList element‑hiding rules.
 * Place this script early in your HTML.
 */
(function() {
    "use strict";

    // ------------------------------------------------------------------
    // 1. List of ad selectors (derived from EasyList)
    // ------------------------------------------------------------------
    const AD_SELECTORS = [
        ${escapedSelectors.map(s => `'${s}'`).join(',\n        ')}
    ];

    // ------------------------------------------------------------------
    // 2. Helper: remove all matching elements
    // ------------------------------------------------------------------
    function removeAds() {
        let removed = 0;
        AD_SELECTORS.forEach(selector => {
            const elements = document.querySelectorAll(selector);
            elements.forEach(el => {
                if (el.parentNode) {
                    el.parentNode.removeChild(el);
                    removed++;
                }
            });
        });
        if (removed > 0) {
            console.log(\`[AdBlocker] Removed \${removed} ad element(s)\`);
        }
    }

    // ------------------------------------------------------------------
    // 3. Initial clean‑up (run as soon as DOM is ready)
    // ------------------------------------------------------------------
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', removeAds);
    } else {
        removeAds();
    }

    // ------------------------------------------------------------------
    // 4. Watch for future ads (MutationObserver)
    // ------------------------------------------------------------------
    const observer = new MutationObserver(() => {
        clearTimeout(observer._timer);
        observer._timer = setTimeout(removeAds, 200);
    });

    observer.observe(document.documentElement, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: ['class', 'id']
    });

    console.log('[AdBlocker] Active – blocking known ad selectors.');
})();`;

    fs.writeFile(outputPath, clientScript, 'utf8', (err) => {
        if (err) {
            console.error('[build] Failed to write adblocker.js:', err.message);
            return;
        }
        console.log('[build] Successfully created', outputPath);
        console.log('[build] You can now include this file in your HTML:');
        console.log(`  <script src="${path.basename(outputPath)}"></script>`);
    });
}

// ------------------------------------------------------------------
// 4. Main: download, parse, generate
// ------------------------------------------------------------------
function main() {
    const outputFile = path.join(__dirname, 'adblocker.js');

    downloadEasyList((err, data) => {
        if (err) {
            console.error('[build] Aborting due to download error.');
            process.exit(1);
        }

        const selectors = parseEasyList(data);
        generateAdblocker(selectors, outputFile);
    });
}

// Run the script
main();